# Generated by Django 4.2.8 on 2024-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_healthrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthrecord',
            old_name='meal_content',
            new_name='breakfast_content',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='dinner_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='lunch_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='other_meal_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
