# Generated by Django 4.2.8 on 2024-02-02 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_meal_content_healthrecord_breakfast_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
