# Generated by Django 4.2.8 on 2024-02-07 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_entry_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
