# Generated by Django 4.2.8 on 2024-02-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_userprofile_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblink',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='weblink',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
