# Generated by Django 4.2.8 on 2024-02-14 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_userrewards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weblink',
            options={'permissions': [('can_view_weblink', 'Can view web link')]},
        ),
        migrations.RemoveField(
            model_name='weblink',
            name='parent',
        ),
        migrations.AlterField(
            model_name='weblink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
