# Generated by Django 4.2.8 on 2024-02-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_weblink_options_remove_weblink_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_hours_hour', models.IntegerField()),
                ('sleep_hours_minute', models.IntegerField()),
                ('physical_condition', models.IntegerField()),
                ('stress_level', models.IntegerField()),
                ('hydration_amount', models.IntegerField()),
                ('breakfast_content', models.CharField(max_length=100)),
                ('lunch_content', models.CharField(max_length=100)),
                ('dinner_content', models.CharField(max_length=100)),
                ('other_meal_content', models.CharField(max_length=100)),
                ('training_content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
