# Generated by Django 4.2.8 on 2024-02-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
