# Generated by Django 4.2.8 on 2024-02-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_healthrecord_physical_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='stress_level',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
