# Generated by Django 4.2.8 on 2024-02-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_healthrecord_stress_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='hydration_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
