# Generated by Django 4.2.8 on 2024-02-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_healthrecord_hydration_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='sleep_hours',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
