# Generated by Django 4.2.8 on 2024-03-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_userrewards_continuous_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRewards',
        ),
    ]
